apiVersion: v1
kind: Service
metadata:
  name: "vynd-{{.Release.Name }}-api-{{ .Values.env }}"
  labels:
    app: "vynd-{{.Release.Name }}-api-{{ .Values.env }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: "vynd-{{.Release.Name }}-api-{{ .Values.env }}"
